import { NavBar } from '../../components/NavBar'
import { MainContainer, Container } from '../styles'
import Head from 'next/head';
import { apiUrlPost } from '../../services/api';
import { useSession } from "next-auth/react";
import { useState } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link';

const CreatePost = () => {

    const route = useRouter();

    const { data: session } = useSession();

    const [title, setTitle] = useState('');
    const [subtitle, setSubtitle] = useState('');
    const [description, setDescription] = useState('');

    const handleSubmit = async () => {

        const Inserir = {
            "title": `${title}`,
            "subtitle": `${subtitle}`,
            "description": `${description}`,
            "nome_author": `${session.user.name}`,
            "email_author": `${session.user.email}`,
            "foto_author": `${session.user.image}`
        }

        const enviar = await apiUrlPost.post(`/posts_v2`, Inserir);

        if(enviar){
            route.push('/');
        }

    }

    

    return (
        <>
        <Head>
            <title>Personal Blog - Criar</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <NavBar />
        <MainContainer>
            <Container>
                    <input type="text" placeholder="titulo" onChange={(event) => setTitle(event.target.value)} />
                    <input type="text" placeholder="subtitulo" onChange={(event) => setSubtitle(event.target.value)} />
                    <input type="message" placeholder="Messagens" onChange={(event) => setDescription(event.target.value)} />
                    <button onClick={handleSubmit}>Submeter</button>
            </Container>
        </MainContainer>

        </>
    )
}

export default CreatePost;